import type { Metadata } from 'next';
import { title_font, paragraph_font } from '@/config/font';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${paragraph_font.className} ${title_font.className} antialiased`}
      >
        {children}
        <script
          async
          src='https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js'
        ></script>
      </body>
    </html>
  );
}
